DROP DATABASE IF EXISTS LIKES;
CREATE DATABASE LIKES;
USE LIKES;

DROP TABLE IF EXISTS PORTRAITS;
DROP TABLE IF EXISTS USERS;


CREATE TABLE `USERS`(
	`ID`        INT(11)     UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `WX_ID`     VARCHAR(30) NOT NULL COMMENT'微信ID',
  `USERNAME`  VARCHAR(32) NOT NULL COMMENT'用户名',
  `AVATAR`     VARCHAR(30) COMMENT'头像链接',
  `VIP`       TINYINT(1)  NOT NULL DEFAULT 0 COMMENT'会员标签',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '用户表';


CREATE TABLE `PORTRAITS`(
	`PID` INT(11) UNSIGNED NOT NULL COMMENT'头像ID',
  `UID` INT(11) UNSIGNED                   COMMENT'头像来源用户ID',
  `USED_TIME`   TINYINT(5) NOT NULL DEFAULT 0 COMMENT'使用次数',
  PRIMARY KEY (`PID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '头像表';

INSERT INTO USERS(ID,WX_ID,USERNAME,VIP) VALUES (1,1,'SUPER_ADMIN',1);